# Site settings
title: RedELA Investigación - Asociación sin ánimo de lucro
email: coordinela@gmail.com
url: http://redela.org
description: "RedELA es una organización para conseguir fondos para la investigación de la Esclerosis Lateral Amiotrófica. Creada e impulsada por afectados de ELA y sus familiares y amigos."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#333333' #'#000000'
  links: '#BAE6F3' # '#219ab3'

# Footer settings
footer: RedELA Investigación
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: email
    url: mailto:coordinela@gmail.com?Subject=Contribuir%20con%20RedELA
  - title: twitter
    url: https://twitter.com/afectadosela
  - title: facebook
    url: https://www.facebook.com/plataformaafectadosela

# Build settings
markdown: kramdown
permalink: pretty
